logging:
  level:
    root: warn
    performance: info
    com.snw: info

spring:
  application:
    name: spring-jpa-baseline
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.hbm2ddl.auto: update
      hibernate.generate_statistics: false
      hibernate.session_factory.statement_inspector: com.snw.schema.exporter.config.SqlStatementInspector
      hibernate.archive.autodetection=class: class
  datasource:
    url: jdbc:h2:mem:staydb
